; [ This translation created 10-Feb-83 by Version 4.3 ]

	.RADIX  8		; To be safe

CSEG	SEGMENT PUBLIC 'CODESG' 
	ASSUME  CS:CSEG

INCLUDE	IBMRES.INC 

	SUBTTL  Equates and External Declarations
	TITLE   IBMRES - reserved words and tokens (MBASIC 5.28 numbering)
COMMENT	*

--------- --- ---- -- ---------
COPYRIGHT (C) 1982 BY MICROSOFT
--------- --- ---- -- ---------

The reserved word tables were rebuilt so that every token value is the one
used by MBASIC 5.28: statements are single byte tokens 81H..CCH, functions
are FF prefixed.  There are no extended (FE/FD) tokens left; the extended
tables below are empty and only keep the hooks in the crunch, list and
evaluate code well defined.
	*


	.SALL
	.RADIX	10

	EXTRN	CHRGTR:NEAR
	EXTRN	DATEF:NEAR,TIMEF:NEAR
	EXTRN	FCERR:NEAR
	EXTRN	LABBCK:NEAR
	EXTRN	MAKUPL:NEAR
	EXTRN	NOTRFN:NEAR
	EXTRN	PARCHK:NEAR,PLOOP2:NEAR,PPSWRT:NEAR
	EXTRN	RENCRN:NEAR
	EXTRN	TSTANM:NEAR

DSEG	SEGMENT PUBLIC 'DATASG'
	ASSUME DS:DSEG
	EXTRN	FLGOVC:WORD,TEMPA:WORD
DSEG	ENDS

;
; THESE MACRO CALLS DEFINE THE RESWRD VALUES
; AND THE TABLE DISPATCH FOR STATEMENTS AND FUNCTIONS
;
; STATEMENTS:
;

PUBLIC	STMDSP
STMDSP:				;MARKS START OF STATEMENT LIST
	QQ=128

	R2	END,ENDST	;81H
	R	FOR	;82H
	R	NEXT	;83H
	R2	DATA,DATAS	;84H
	R	INPUT	;85H
	R	DIM	;86H
	R	READ	;87H
	R	LET	;88H
	R	GOTO	;89H
	R	RUN	;8AH
	R2	IF,IFS	;8BH
	R	RESTORE	;8CH
	R	GOSUB	;8DH
	R	RETURN	;8EH
	R	REM	;8FH
	R	STOP	;90H
	R	PRINT	;91H
	R	CLEAR	;92H
	R	LIST	;93H
	R2	NEW,SCRATH	;94H
	R2	ON,ONGOTO	;95H
	R	NULL	;96H
	R2	WAIT,FNWAIT	;97H
	R	DEF	;98H
	R	POKE	;99H
	R	CONT	;9AH
	R2	DUMMY,SNERR	;padding (9BH)
	R2	DUMMY,SNERR	;padding (9CH)
	R2	OUT,FNOUT	;9DH
	R	LPRINT	;9EH
	R	LLIST	;9FH
	R2	DUMMY,SNERR	;padding (A0H)
	R2	WIDTH,WIDTHS	;A1H
	R2	ELSE,ELSES	;A2H
	R2	TRON,TON	;A3H
	R2	TROFF,TOFF	;A4H
	R	SWAP	;A5H
	R	ERASE	;A6H
	R	EDIT	;A7H
	R2	ERROR,ERRORS	;A8H
	R	RESUME	;A9H
	R	DELETE	;AAH
	R	AUTO	;ABH
	R2	RENUM,RESEQ	;ACH
	R	DEFSTR	;ADH
	R	DEFINT	;AEH
	R2	DEFSNG,DEFREA	;AFH
	R	DEFDBL	;B0H
	R	LINE	;B1H
	R	BLOAD	;B2H
	R	BSAVE	;B3H
	R	WHILE	;B4H
	R	WEND	;B5H
	R2	CALL,CALLS	;B6H
	R	WRITE	;B7H
	R	COMMON	;B8H
	R	CHAIN	;B9H
	R	OPTION	;BAH
	R2	RANDOMIZE,RANDOM	;BBH
	R2	CALLS,CALLSL	;BCH
	R	SYSTEM	;BDH
	R2	DUMMY,SNERR	;padding (BEH)
	R	OPEN	;BFH
	R	FIELD	;C0H
	R	GET	;C1H
	R	PUT	;C2H
	R	CLOSE	;C3H
	R	LOAD	;C4H
	R	MERGE	;C5H
	R	FILES	;C6H
	R	NAME	;C7H
	R	KILL	;C8H
	R	LSET	;C9H
	R	RSET	;CAH
	R	SAVE	;CBH
	R	RESET	;CCH
PUBLIC	NUMCMD
	NUMCMD=QQ-$END+1
;
; TOKENS
;
;QQ MUST BE SET SO TOKENS START AT RIGHT PLACE
;
	QQ=QQ+1
	T	TO
	T	THEN
PUBLIC	THENTK
	THENTK=QQ
	T	TAB
PUBLIC	TABTK
	TABTK=QQ
	T	STEP
PUBLIC	STEPTK
	STEPTK=QQ
	T	USR
PUBLIC	USRTK
	USRTK=QQ
	T	FN
PUBLIC	FNTK
	FNTK=QQ
	T	SPC
PUBLIC	SPCTK
	SPCTK=QQ
	T	NOT
PUBLIC	NOTTK
	NOTTK=QQ
	T	ERL
PUBLIC	ERLTK
	ERLTK=QQ
	T	ERR
PUBLIC	ERCTK
	ERCTK=QQ
	T	STRING$
	T	USING
PUBLIC	USINTK
	USINTK=QQ
	T	<INSTR>
PUBLIC	INSRTK
	INSRTK=QQ
	T	DUMMY
PUBLIC	SNGQTK
	SNGQTK=QQ
	T	VARPTR
	T	INKEY$
;
; OPERATORS
;
	QQ=QQ+17		;unused tokens DEH..EEH
	T	DUMMY
PUBLIC	GREATK
	GREATK=QQ
	T	DUMMY
PUBLIC	EQULTK
	EQULTK=QQ
	T	DUMMY
PUBLIC	LESSTK
	LESSTK=QQ
	T	DUMMY
PUBLIC	PLUSTK
	PLUSTK=QQ
	T	DUMMY
PUBLIC	MINUTK
	MINUTK=QQ
	T	DUMMY
PUBLIC	MULTK
	MULTK=QQ
	T	DUMMY
PUBLIC	DIVTK
	DIVTK=QQ
	T	DUMMY
PUBLIC	EXPTK
	EXPTK=QQ
	T	AND
	T	OR
	T	XOR
	T	EQV
	T	IMP
	T	MOD
	T	DUMMY
PUBLIC	IDIVTK
	IDIVTK=QQ
PUBLIC	LSTOPK
	LSTOPK=QQ+1-PLUSTK
;
; FUNCTIONS - 2 byte tokens, the 1st byte is FF
;
	QQ=128
PUBLIC	FUNDSP
FUNDSP:

	R	LEFT$
PUBLIC	ONEFUN
	ONEFUN=QQ
	R	RIGHT$
	R	MID$
PUBLIC	MIDTK
	MIDTK=QQ
	R	SGN
	R2	INT,VINT
	R2	ABS,ABSFN
	R	SQR
PUBLIC	SQRTK
	SQRTK=QQ
	R	RND
	R	SIN
	R	LOG
	R	EXP
	R	COS
	R	TAN
	R	ATN
PUBLIC	ATNTK
	ATNTK=QQ
	R	FRE
	R2	INP,FNINP
	R	POS
	R	LEN
	R	STR$
	R	VAL
	R	ASC
	R	CHR$
	R	PEEK
	R	SPACE$
	R2	OCT$,STRO$
	R2	HEX$,STRH$
	R	LPOS
PUBLIC	LASNUM
	LASNUM=QQ
	R2	CINT,FRCINT
	R2	CSNG,FRCSNG
	R2	CDBL,FRCDBL
	R2	FIX,FIXER
PUBLIC	$FIX
	$FIX=QQ
	R2	DUMMY,FCERR	;unused function 20H
	R2	DUMMY,FCERR	;unused function 21H
	R2	DUMMY,FCERR	;unused function 22H
	R2	DUMMY,FCERR	;unused function 23H
	R2	DUMMY,FCERR	;unused function 24H
	R2	DUMMY,FCERR	;unused function 25H
	R2	DUMMY,FCERR	;unused function 26H
	R2	DUMMY,FCERR	;unused function 27H
	R2	DUMMY,FCERR	;unused function 28H
	R2	DUMMY,FCERR	;unused function 29H
	R2	DUMMY,FCERR	;unused function 2AH
	R	CVI
	R	CVS
	R	CVD
	R2	DUMMY,FCERR	;unused function 2EH
	R	EOF
	R	LOC
	R	LOF
	R	MKI$
	R	MKS$
	R	MKD$
	R2	DUMMY,FCERR	;unused function 35H
	R2	DUMMY,FCERR	;unused function 36H
	R2	DUMMY,FCERR	;unused function 37H
	R2	DUMMY,FCERR	;unused function 38H
	R2	DUMMY,FCERR	;unused function 39H
	R2	DUMMY,FCERR	;unused function 3AH
	R2	DUMMY,FCERR	;unused function 3BH
	R2	DUMMY,FCERR	;unused function 3CH
	R2	DUMMY,FCERR	;unused function 3DH
	R2	DUMMY,FCERR	;unused function 3EH
	R2	DUMMY,FCERR	;unused function 3FH
	R2	DUMMY,FCERR	;unused function 40H
	R2	DUMMY,FCERR	;unused function 41H
	R2	DUMMY,FCERR	;unused function 42H
	R2	DUMMY,FCERR	;unused function 43H
	R2	DUMMY,FCERR	;unused function 44H
	R2	DUMMY,FCERR	;unused function 45H
	R2	DUMMY,FCERR	;unused function 46H
	R2	DUMMY,FCERR	;unused function 47H
	R2	DUMMY,FCERR	;unused function 48H
	R2	DUMMY,FCERR	;unused function 49H
	R2	DUMMY,FCERR	;unused function 4AH
	R2	DUMMY,FCERR	;unused function 4BH
	R2	DUMMY,FCERR	;unused function 4CH
	R2	DUMMY,FCERR	;unused function 4DH
	R2	DUMMY,FCERR	;unused function 4EH
	R2	DUMMY,FCERR	;unused function 4FH
	R2	DATE$,DATEF
	R2	TIME$,TIMEF

;
; THE FOLLOWING TABLES ARE THE ALPHABETIC DISPATCH TABLE
; FOLLOWED BY THE RESERVED WORD TABLE ITSELF
;
PUBLIC	ALPTAB
ALPTAB:
	DW	OFFSET ATAB
	DW	OFFSET BTAB
	DW	OFFSET CTAB
	DW	OFFSET DTAB
	DW	OFFSET ETAB
	DW	OFFSET FTAB
	DW	OFFSET GTAB
	DW	OFFSET HTAB
	DW	OFFSET ITAB
	DW	OFFSET JTAB
	DW	OFFSET KTAB
	DW	OFFSET LTAB
	DW	OFFSET MTAB
	DW	OFFSET NTAB
	DW	OFFSET OTAB
	DW	OFFSET PTAB
	DW	OFFSET QTAB
	DW	OFFSET RTAB
	DW	OFFSET STAB
	DW	OFFSET TTAB
	DW	OFFSET UTAB
	DW	OFFSET VTAB
	DW	OFFSET WTAB
	DW	OFFSET XTAB
	DW	OFFSET YTAB
	DW	OFFSET ZTAB
PUBLIC	RESLST
RESLST:

ATAB:
	Q	AUTO
	Q	AND
	QF	ABS
	QF	ATN
	QF	ASC
	DB	0
BTAB:
	Q	BSAVE
	Q	BLOAD
	DB	0
CTAB:
	Q	CLOSE
	Q	CONT
	Q	CLEAR
	QF	CINT
	QF	CSNG
	QF	CDBL
	QF	CVI
	QF	CVS
	QF	CVD
	QF	COS
	QF	CHR$
	Q	CALLS
	Q	CALL
	Q	COMMON
	Q	CHAIN
	DB	0
DTAB:
	Q	DELETE
	Q	DATA
	Q	DIM
	Q	DEFSTR
	Q	DEFINT
	Q	DEFSNG
	Q	DEFDBL
	Q	DEF
	QF	DATE$
	DB	0
ETAB:
	Q	ELSE
	Q	END
	Q	ERASE
	Q	EDIT
	Q	ERROR
	Q	ERL
	Q	ERR
	QF	EXP
	QF	EOF
	Q	EQV
	DB	0
FTAB:
	Q	FOR
	Q	FIELD
	Q	FILES
	Q	FN
	QF	FRE
	QF	FIX
	DB	0
GTAB:
	Q	GOTO
	DB	"O"
	DB	" "
	DB	"T"
	DB	"O"+128D
	DB	OFFSET $GOTO
	Q	GOSUB
	Q	GET
	DB	0
HTAB:
	QF	HEX$
	DB	0
ITAB:
	Q	INPUT
	Q	IF
	Q	<INSTR>
	QF	INT
	QF	INP
	Q	IMP
	Q	INKEY$
	DB	0
JTAB:
	DB	0
KTAB:
	Q	KILL
	DB	0
LTAB:
	Q	LPRINT
	Q	LLIST
	QF	LPOS
	Q	LET
	Q	LINE
	Q	LOAD
	Q	LSET
	Q	LIST
	QF	LOG
	QF	LOC
	QF	LEN
	QF	LEFT$
	QF	LOF
	DB	0
MTAB:
	Q	MERGE
	Q	MOD
	QF	MKI$
	QF	MKS$
	QF	MKD$
	QF	MID$
	DB	0
NTAB:
	Q	NEXT
	Q	NULL
	Q	NAME
	Q	NEW
	Q	NOT
	DB	0
OTAB:
	Q	OPEN
	Q	OUT
	Q	ON
	Q	OR
	QF	OCT$
	Q	OPTION
	DB	0
PTAB:
	Q	PRINT
	Q	PUT
	Q	POKE
	QF	POS
	QF	PEEK
	DB	0
QTAB:
	DB	0
RTAB:
	Q	RETURN
	Q	READ
	Q	RUN
	Q	RESTORE
	Q	REM
	Q	RESUME
	Q	RSET
	QF	RIGHT$
	QF	RND
	Q	RENUM
	Q	RESET
	Q	RANDOMIZE
	DB	0
STAB:
	Q	STOP
	Q	SWAP
	Q	SAVE
	DB	"P"
	DB	"C"
	DB	"("+128D
	DB	OFFSET SPCTK
	Q	STEP
	QF	SGN
	QF	SQR
	QF	SIN
	QF	STR$
	Q	STRING$
	QF	SPACE$
	Q	SYSTEM
	DB	0
TTAB:
	Q	THEN
	Q	TRON
	Q	TROFF
	DB	"A"
	DB	"B"
	DB	"("+128D
	DB	OFFSET TABTK
	Q	TO
	QF	TAN
	QF	TIME$
	DB	0
UTAB:
	Q	USING
	Q	USR
	DB	0
VTAB:
	QF	VAL
	Q	VARPTR
	DB	0
WTAB:
	Q	WIDTH
	Q	WAIT
	Q	WHILE
	Q	WEND
	Q	WRITE
	DB	0
XTAB:
	Q	XOR
	DB	0
YTAB:
	DB	0
ZTAB:
	DB	0
PUBLIC	SPCTAB
SPCTAB:
	DB	"+"+128D
	DB	OFFSET PLUSTK
	DB	"-"+128D
	DB	OFFSET MINUTK
	DB	"*"+128D
	DB	OFFSET MULTK
	DB	"/"+128D
	DB	OFFSET DIVTK
	DB	"^"+128D
	DB	OFFSET EXPTK
	DB	"\"+128D
	DB	OFFSET IDIVTK
	DB	"'"+128D
	DB	OFFSET SNGQTK
	DB	62+128D
	DB	OFFSET GREATK
	DB	"="+128D
	DB	OFFSET EQULTK
	DB	60+128D
	DB	OFFSET LESSTK
	DB	0

	SUBTTL  Extended reserved words (none: kept empty for the FE/FD hooks)

	QQ=128D
STMDSX:
	DW	OFFSET FCERR
FUNDSX:
	DW	OFFSET FCERR
PUBLIC	ALPTAX
ALPTAX:
	DW	OFFSET EMPTAB
	DW	OFFSET EMPTAB
	DW	OFFSET EMPTAB
	DW	OFFSET EMPTAB
	DW	OFFSET EMPTAB
	DW	OFFSET EMPTAB
	DW	OFFSET EMPTAB
	DW	OFFSET EMPTAB
	DW	OFFSET EMPTAB
	DW	OFFSET EMPTAB
	DW	OFFSET EMPTAB
	DW	OFFSET EMPTAB
	DW	OFFSET EMPTAB
	DW	OFFSET EMPTAB
	DW	OFFSET EMPTAB
	DW	OFFSET EMPTAB
	DW	OFFSET EMPTAB
	DW	OFFSET EMPTAB
	DW	OFFSET EMPTAB
	DW	OFFSET EMPTAB
	DW	OFFSET EMPTAB
	DW	OFFSET EMPTAB
	DW	OFFSET EMPTAB
	DW	OFFSET EMPTAB
	DW	OFFSET EMPTAB
	DW	OFFSET EMPTAB
RESLSX:
EMPTAB:
	DB	0

	PUBLIC	NUMGFN,BOTCON,TOPCON,$RNDFN,$DATCO,$REMCO,NMREL
	PUBLIC	$CHRFN,$CSNGF,$CDBLF
	NUMGFN=(2*MIDTK)-(2*ONEFUN)+1
	BOTCON=(SQRTK-ONEFUN)*2
	TOPCON=(ATNTK-ONEFUN)*2+1
	$RNDFN=$RND-ONEFUN
	$DATCO=$DATA-":"
	$REMCO=$REM-":"
	NMREL=LESSTK-GREATK+1
	$CHRFN=$CHR$-ONEFUN
	$CSNGF=$CSNG-ONEFUN
	$CDBLF=$CDBL-ONEFUN


	SUBTTL  CRUNCH code to handle extended reserved words

PUBLIC	CRUNCX
CRUNCX:	POP	BX		;GET BACK SOURCE POINTER
	PUSH	BX		;TO TRY AGAIN
	DEC	BX		;POINT AT CHARACTER
	CALL	MAKUPL		;CONVERT TO UPPER CASE
	MOV	BX,OFFSET ALPTAX	;GET POINTER TO ALPHA DISPATCH TABLE
	SUB	AL,LOW "A"	;SUBTRACT ALPHA OFFSET
	ADD	AL,AL		;MULTIPLY BY TWO
	MOV	CL,AL		;SAVE OFFSET IN [C] FOR DAD.
	MOV	CH,LOW 0	;MAKE HIGH PART OF OFFSET ZERO
	ADD	BX,CX		;ADD TO TABLE ADDRESS
	INS86	56
	MOV	DX,[BX]		;GET POINTER IN [D,E]
	POP	BX		;GET BACK SOURCE POINTER
TRYAGA:	PUSH	BX		;SAVE TXTPTR TO START OF SEARCH AREA
LOPPSI:
	CALL	MAKUPL		;TRANSLATE THIS CHAR TO UPPER CASE
	MOV	CL,AL		;SAVE CHAR IN [C]
	INS86	213,362,56,254	;FETCH FROM CODE SEGMENT
	AND	AL,LOW 127	;GET RID OF HIGH BIT
	JNZ	SHORT ??L000
	JMP	NOTRFN		;IF=0 THEN END OF THIS CHARS RESLT
??L000:
	INC	BX		;BUMP SOURCE POINTER
	CMP	AL,CL		;COMPARE TO CHAR FROM SOURCE LINE
	JNZ	SHORT LOPSKP	;IF NO MATCH, SEARCH FOR NEXT RESWRD
	INS86	213,362,56,254	;FETCH FROM CODE SEGMENT
	INC	DX		;BUMP RESLST POINTER
	OR	AL,AL		;SET CC'S
	JS	SHORT ??L001
	JMP	LOPPSI		;SEE IF REST OF CHARS MATCH
??L001:
	INS86	213,362,56,254	;FETCH FROM CODE SEGMENT
	CALL	MAKUPL		;GET NEXT CHAR IN LINE (MC 6/22/80)
	CMP	AL,LOW "."	;IS IT A DOT
	JZ	SHORT ISVARS	;YES
	CALL	TSTANM		;IS IT A LETTER IMMEDIATELY
				;FOLLOWING RESWRD
ISVARS:	MOV	AL,LOW 0	;SET DONUM TO -1
	JNAE	SHORT ??L002
	JMP	NOTRFN		;IF ALPHA, CANT BE RESERVED WORD
??L002:
	POP	AX		;GET RID OF SAVED [H,L]
	INS86	213,362,56,254	;FETCH FROM CODE SEGMENT
	OR	AL,AL		;SET CC'S
	POP	CX		;GET CHAR COUNT OFF STACK
	POP	DX		;GET DEPOSIT POINTER OFF STACK
	JNS	SHORT ??L003
	JMP	NOTFNT		;IF MINUS, WASNT FUNCTION TOKEN
??L003:
	OR	AL,LOW 200O	;MAKE HIGH ORDER BIT ONE
	STC			;AND FORCE LEADER BYTE TO BE 375
NOTFNT:	PUSH	AX		;SAVE FN CHAR
	MOV	AL,LOW 376O	;GET BYTE WHICH PRECEEDS FNS
	SBB	AL,LOW 0	;MAKE FUNCTION LEADER 375
	JMP	RENCRN		;REENTER CRUNCH WITH NEW RESERVED WORD

LOPSKP:	POP	BX		;RESTORE UNDEFILED TEXT POINTER
LOPSK2:
	INS86	213,362,56,254	;FETCH FROM CODE SEGMENT
	INC	DX		;BUMP RESLST POINTER
	OR	AL,AL		;SET CC'S
	JS	SHORT ??L004
	JMP	LOPSK2		;NOT END OF RESWRD, KEEP SKIPPING
??L004:
	INC	DX		;POINT AFTER TOKEN
	JMP	TRYAGA		;TRY ANOTHER RESWRD

	SUBTTL  LIST code for extended reserved words

BUFRET:	RET	

NEWFUN:	MOV	AL,BYTE PTR [BX]	;GET FUNCTION NUMBER
	AND	AL,LOW 177O	;TAKE OFF HIGH BIT
	JMP	SHORT BUFCON

PUBLIC	LISTX
LISTX:	CMP	AL,LOW 375O	;IS IT A NEW FUNCTION
	JZ	SHORT NEWFUN
	CMP	AL,LOW 376O	;IS IT A NEW STATEMENT
	JNZ	SHORT BUFRET	;NO, JUST CONTINUE NORMAL PATH
	MOV	AL,BYTE PTR [BX]	;GET NUMBER OF STATEMENT
BUFCON:	POP	BX		;Get rid of the return address.
	MOV	BX,OFFSET RESLSX-1	;GET PTR TO START OF RESERVED WORD LIST
	MOV	CH,AL		;SAVE THIS CHAR IN [B]
	MOV	CL,LOW OFFSET "A"-1	;INIT LEADING CHAR VALUE
RESSR3:	INC	CL		;BUMP LEADING CHAR VALUE.
RESSR1:	INC	BX		;BUMP POINTER INTO RESLST
RESSRC:	MOV	DH,BH		;SAVE PTR TO START OF THIS RESWRD
	MOV	DL,BL
RESSR2:
	INS86	56		;FETCH FROM CODE SEGMENT
	MOV	AL,BYTE PTR [BX]	;GET CHAR FROM RESLST
	OR	AL,AL		;SET CC'S
	JZ	SHORT RESSR3	;IF END OF THIS CHARS TABLE,
				;GO BACK & BUMP C
	LAHF
	INC	BX		;BUMP SOURCE PTR
	SAHF
	JS	SHORT ??L005
	JMP	RESSR2		;IF NOT END OF THIS RESWRD,
??L005:
				;THEN KEEP LOOKING
	INS86	56		;FETCH FROM CODE SEGMENT
	MOV	AL,BYTE PTR [BX]	;GET PTR TO RESERVED WORD VALUE
	CMP	AL,CH		;SAME AS THE ONE WE SEARCH FOR?
	JNZ	SHORT RESSR1	;NO, KEEP LOOKING.
	XCHG	BX,DX		;SAVE FOUND PTR IN [H,L]
	MOV	AL,CL		;GET LEADING CHAR
	POP	DX		;RESTORE LINE CHAR COUNT
	POP	CX		;RESTORE DEPOSIT PTR
	MOV	DL,AL		;SAVE LEADING CHAR IN [E]
;
; CODE BELOW NOT NEEDED SINCE NO SPECIAL REVERVED WORDS IN HOOK TABLE
;
;       CPI     "Z"+1           ;WAS IT A SPECIAL CHAR?
;       JRNZ    NTSPCH          ;NON-SPECIAL CHAR
;       XRA     A               ;SET NON-SPECIAL
;       STA     TEMPA
;       JMPR    MORPUR          ;PRINT IT
NTSPCH:	MOV	AL,BYTE PTR TEMPA	;WHAT DID WE DO LAST?
	OR	AL,AL		;SPECIAL?
	MOV	AL,LOW 255	;FLAG IN RESERVED WORD
	MOV	BYTE PTR TEMPA,AL	;CLEAR FLAG
MORLNZ:	JZ	SHORT MORLN0	;GET CHAR AND PROCEED
	MOV	AL,LOW " "	;PUT SPACE IN BUFFER
	MOV	DI,CX
	STOSB
	INC	CX
	DEC	DH		;ANY SPACE LEFT IN BUFFER
	JNZ	SHORT ??L006
	JMP	PPSWRT		;NO, RETURN
??L006:
MORLN0:	MOV	AL,DL
	JMP	SHORT MORLN1	;CONTINUE
MORPUR:
	INS86	56		;FETCH FROM CODE SEGMENT
	MOV	AL,BYTE PTR [BX]	;GET BYTE FROM RESWRD
	INC	BX		;BUMP POINTER
MORLNP:	MOV	DL,AL		;SAVE CHAR
MORLN1:	AND	AL,LOW 177O	;AND OFF HIGH ORDER BIT FOR DISK & EDIT
	MOV	DI,CX
	STOSB			;STORE THIS CHAR
	INC	CX		;BUMP PTR
	DEC	DH		;BUMP DOWN REMAINING CHAR COUNT
	JNZ	SHORT ??L007
	JMP	PPSWRT		;IF END OF LINE, JUST RETURN
??L007:
	OR	AL,DL		;SET CC'S
	JS	SHORT ??L008
	JMP	MORPUR		;END OF RESWRD?
??L008:
	POP	BX		;RESTORE SOURCE PTR.
	INC	BX		;SKIP OVER RESERVED WORD
	JMP	PLOOP2		;GET NEXT CHAR FROM LINE

	SUBTTL  Statements that start with a function token (DATE$=, TIME$=)

	EXTRN	DATES:NEAR,TIMES:NEAR

PUBLIC	NEWSTX
NEWSTX:	CMP	AL,LOW OFFSET 377O-201O	;FUNCTION?
	JNZ	SHORT GIIRET
	POP	CX		;Put return address into B.
	INC	BX
	MOV	AL,BYTE PTR [BX]
	CMP	AL,LOW OFFSET $DATE$	;DATE$ as stmt?
	JNZ	SHORT NTDATS
	CALL	CHRGTR
	JMP	DATES
NTDATS:	CMP	AL,LOW OFFSET $TIME$	;TIME$ as stmt?
	JNZ	SHORT NTTIMS
	CALL	CHRGTR
	JMP	TIMES
NTTIMS:	DEC	BX
	MOV	AL,LOW OFFSET 377O-201O
	PUSH	CX		;Put the return address back on.
GIIRET:	RET			;MID$ OR SYNTAX ERROR

	SUBTTL  DATE$ and TIME$ used as functions (no argument list)

PUBLIC	EVALX
EVALX:	CMP	AL,LOW 377O
	JNZ	SHORT EVALXR	;not a function token
	INC	BX
	MOV	AL,BYTE PTR [BX]
	CMP	AL,LOW OFFSET $DATE$
	JZ	SHORT DATEV	;Brif DATE$
	CMP	AL,LOW OFFSET $TIME$
	JZ	SHORT TIMEV	;Brif TIME$
	DEC	BX
	MOV	AL,BYTE PTR [BX]
EVALXR:	RET	

DATEV:	POP	CX		;Get rid of the hook return address.
	JMP	DATEF		;Do DATE function.

TIMEV:	POP	CX		;Get rid of the hook return address.
	JMP	TIMEF		;Do TIME$ function.

CSEG	ENDS
	END
